export const GET_TICKET_ROOM_LIST_REQUEST = "GET_TICKET_ROOM_LIST_REQUEST";
export const GET_TICKET_ROOM_LIST_SUCCESS = "GET_TICKET_ROOM_LIST_SUCCESS";
export const GET_TICKET_ROOM_LIST_FAILURE = "GET_TICKET_ROOM_LIST_FAILURE";

export const BOOKING_TICKET_REQUEST = "BOOKING_TICKET_REQUEST";
export const BOOKING_TICKET_SUCCESS = "BOOKING_TICKET_SUCCESS";
export const BOOKING_TICKET_FAILURE = "BOOKING_TICKET_FAILURE";
