export const GET_TICKET_ROOM_LIST_REQUEST = "GET_TICKET_ROOM_LIST_REQUEST";
export const GET_TICKET_ROOM_LIST_SUCCESS = "GET_TICKET_ROOM_LIST_SUCCESS";
export const GET_TICKET_ROOM_LIST_FAILURE = "GET_TICKET_ROOM_LIST_FAILURE";
