export const GET_THEATER_SYSTEM_REQUEST = "GET_THEATER_SYSTEM_REQUEST";
export const GET_THEATER_SYSTEM_SUCCESS = "GET_THEATER_SYSTEM_SUCCESS";
export const GET_THEATER_SYSTEM_FAILURE = "GET_THEATER_SYSTEM_FAILURE";

export const GET_THEATER_CLUSTER_REQUEST = "GET_THEATER_CLUSTER_REQUEST";
export const GET_THEATER_CLUSTER_SUCCESS = "GET_THEATER_CLUSTER_SUCCESS";
export const GET_THEATER_CLUSTER_FAILURE = "GET_THEATER_CLUSTER_FAILURE";

export const GET_INFO_THEATER_SYSTEM_SHOWTIMES_REQUEST = "GET_INFO_THEATER_SYSTEM_SHOWTIMES_REQUEST";
export const GET_INFO_THEATER_SYSTEM_SHOWTIMES_SUCCESS = "GET_INFO_THEATER_SYSTEM_SHOWTIMES_SUCCESS";
export const GET_INFO_THEATER_SYSTEM_SHOWTIMES_FAILURE = "GET_INFO_THEATER_SYSTEM_SHOWTIMES_FAILURE";